# config/yaml/Usuario.dcm.yml
Usuario:
  type: entity
  table: usuario
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    login:
      type: string
    email:
      type: string
    password:
      type: string